# Gradle Properties
org.gradle.jvmargs = -Xmx2G
org.gradle.configuration-cache=true

# Gradle Plugins
spotless_version = 6.25.0
remotesign_version = 0.4.0
checkstyle_tool_version = 10.21.1
central_publishing_version = 0.1.7

# Project Properties
version = 0.9.0

# Dependencies
asm_version = 9.7.1
tiny_remapper_version = 0.10.4
jetbrains_annotations_version = 26.0.1
junit_jupiter_version = 5.11.4
srgutils_version = 1.0.9
lorenz_version = 0.5.8
