pluginManagement {
    repositories {
        maven {
            name = 'Fabric'
            url = 'https://maven.fabricmc.net/'
        }
        mavenCentral()
        gradlePluginPortal()
    }
	plugins {
		id 'com.diffplug.spotless' version "${spotless_version}"
		id 'me.modmuss50.remotesign' version "${remotesign_version}"
		id 'dev.lukebemish.central-portal-publishing' version "${central_publishing_version}"
	}
}

rootProject.name = 'mapping-io'

include 'mapping-io-extras'
