name: Build
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/setup-java@v4
        with:
          java-version: '25'
          distribution: 'microsoft'
      - uses: actions/checkout@v4
      - uses: gradle/actions/wrapper-validation@v4
      - run: ./gradlew build --stacktrace --warning-mode fail
