name: Release
on: [workflow_dispatch] # Manual trigger
jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/setup-java@v4
        with:
          java-version: '25'
          distribution: 'microsoft'
      - uses: actions/checkout@v4
      - uses: gradle/actions/wrapper-validation@v4
      - run: ./gradlew checkVersion build signJar publish --stacktrace
        env:
          MAVEN_URL: ${{ secrets.MAVEN_URL }}
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
          MAVEN_CENTRAL_URL: ${{ secrets.MAVEN_CENTRAL_URL }}
          MAVEN_CENTRAL_USERNAME: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
          MAVEN_CENTRAL_PASSWORD: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
          SIGNING_SERVER: ${{ secrets.SIGNING_SERVER }}
          SIGNING_PGP_KEY: ${{ secrets.SIGNING_PGP_KEY }}
          SIGNING_JAR_KEY: ${{ secrets.SIGNING_JAR_KEY }}
